import { createHash } from "node:crypto";
import { createPlugin } from "@qping/plugin-bus/node";
import { mytoolsI18n } from "@qping/plugin-bus/i18n";
import { renderTemplateTrees, type TemplateView } from "./templates.mjs";

type CreateInput = {
  name: string;
  pluginId: string;
  author: string;
  pluginType: "standard" | "custom-ui";
};

function pluginKey(input: CreateInput) {
  return input.pluginId.split(/[^a-z0-9]+/i).filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1)).join("");
}

function sourceHash(defaultValue: string) {
  return `sha256:${createHash("sha256").update(defaultValue).digest("hex")}`;
}

function templateView(input: CreateInput): TemplateView {
  const keyRoot = `Plugin.${pluginKey(input)}`;
  const subtitle = "Generated by MyTools Create Plugin";

  return {
    customUi: input.pluginType === "custom-ui",
    name: input.name,
    nameJson: JSON.stringify(input.name),
    authorJson: JSON.stringify(input.author),
    pluginId: input.pluginId,
    pluginIdJson: JSON.stringify(input.pluginId),
    packageNameJson: JSON.stringify(`mytools-plugin-${input.pluginId}`),
    resultIdJson: JSON.stringify(`${input.pluginId}:result`),
    keyRoot,
    subtitle,
    subtitleJson: JSON.stringify(subtitle),
    subtitleHash: sourceHash(subtitle),
    nameHash: sourceHash(input.name),
    detailQueryHash: sourceHash("Current query"),
    detailReadyHash: sourceHash("Ready")
  };
}

function filesFor(input: CreateInput): Record<string, string> {
  const trees = input.pluginType === "custom-ui" ? ["common", "custom-ui"] : ["common"];
  return renderTemplateTrees(trees, templateView(input));
}

const plugin = createPlugin();
plugin
  .initialize((params) => { mytoolsI18n.configure(params); return {}; })
  .handle("createPlugin", async (payload: CreateInput) => plugin.hostCall("development.create", { ...payload, files: filesFor(payload) }))
  .handle("listDevelopmentPlugins", async () => plugin.hostCall("development.list"))
  .handle("refreshDevelopmentPlugins", async () => plugin.hostCall("development.refresh"))
  .handle("openFolder", async (payload: { sourcePath: string }) => plugin.hostCall("development.openFolder", payload))
  .handle("openCode", async (payload: { sourcePath: string }) => plugin.hostCall("development.openCode", payload))
  .start();
