import { createPlugin } from "@qping/plugin-bus/node";
import { mytoolsI18n } from "@qping/plugin-bus/i18n";
import { renderTemplateTrees, type TemplateView } from "./templates.mjs";

const AI_CHAT_HOST_TIMEOUT_MS = 20 * 60_000;

type CreateInput = {
  name: string;
  pluginId: string;
  pluginType: "standard" | "custom-ui";
};

function pluginKey(input: CreateInput) {
  return input.pluginId.split(/[^a-z0-9]+/i).filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1)).join("");
}

function templateView(input: CreateInput): TemplateView {
  const keyRoot = `Plugin.${pluginKey(input)}`;
  const subtitle = "Generated by MyTools Create Plugin";

  return {
    customUi: input.pluginType === "custom-ui",
    name: input.name,
    nameJson: JSON.stringify(input.name),
    pluginId: input.pluginId,
    pluginIdJson: JSON.stringify(input.pluginId),
    packageNameJson: JSON.stringify(`mytools-plugin-${input.pluginId}`),
    resultIdJson: JSON.stringify(`${input.pluginId}:result`),
    keyRoot,
    subtitle,
    subtitleJson: JSON.stringify(subtitle)
  };
}

function filesFor(input: CreateInput): Record<string, string> {
  const trees = input.pluginType === "custom-ui" ? ["common", "custom-ui"] : ["common"];
  return renderTemplateTrees(trees, templateView(input));
}

const plugin = createPlugin();
plugin
  .initialize((params) => { mytoolsI18n.configure(params); return {}; })
  .handle("validatePlugin", async (payload: Pick<CreateInput, "name" | "pluginId">) =>
    plugin.hostCall("development.validate", payload))
  .handle("createPlugin", async (payload: CreateInput) => plugin.hostCall("development.create", { ...payload, files: filesFor(payload) }))
  .handle("listDevelopmentPlugins", async () => plugin.hostCall("development.list"))
  .handle("deleteDevelopmentPlugin", async (payload: { pluginId: string }) => plugin.hostCall("development.delete", payload))
  .handle("refreshDevelopmentPlugins", async () => plugin.hostCall("development.refresh"))
  .handle("openFolder", async (payload: { sourcePath: string }) => plugin.hostCall("development.openFolder", payload))
  .handle("openCode", async (payload: { sourcePath: string }) => plugin.hostCall("development.openCode", payload))
  .handle("startDebug", async (payload: { pluginId: string }) => plugin.hostCall("development.startDebug", payload, 180_000))
  .handle("startPluginWatch", async (payload: { pluginId: string }) => plugin.hostCall("development.watch.start", payload, 180_000))
  .handle("getPluginWatchLogs", async (payload: { pluginId: string; count?: number }) => plugin.hostCall("development.watch.logs", payload))
  .handle("getMyToolsLogs", async (payload: { count?: number }) => plugin.hostCall("development.logs", payload))
  .handle("publishPlugin", async (payload: { pluginId: string }) => plugin.hostCall("development.publish", payload, 180_000))
  .handle("getAiStatus", async () => plugin.hostCall("development.ai.status"))
  .handle("chatWithAi", async (payload: { sessionId?: string; message: string; selectedPluginId?: string }) =>
    plugin.hostCall("development.ai.chat", payload, AI_CHAT_HOST_TIMEOUT_MS))
  .handle("getAiProgress", async (payload: { sessionId: string; afterSequence: number }) =>
    plugin.hostCall("development.ai.progress", payload, 20_000))
  .handle("clearAiConversation", async (payload: { sessionId?: string }) =>
    plugin.hostCall("development.ai.clear", payload))
  .start();
