<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>MyTools.Plugins</RootNamespace>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Interop.IWshRuntimeLibrary" />
    <PackageReference Include="Lucene.Net" />
    <PackageReference Include="Lucene.Net.Analysis.Common" />
    <PackageReference Include="Lucene.Net.QueryParser" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Syn.Oryzer" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyTools.Common\MyTools.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Plugins\Translator\WordNet\Dict\*.*" />
    <None Update="Examples\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Examples\**\*.*" Exclude="Examples\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Examples\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>
</Project>
